import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { deletePlatformSolo, deleteSoloSubscription, listFreelancers, platformCreateSolo, updateSoloStatus, updateSoloSubscription } from '../../services/company.js';

const plans = [['SOLO_FREE', 'Solo Free'], ['SOLO_PRO', 'Solo Pro'], ['SOLO_BUSINESS', 'Solo Business']];
const blankForm = { name: '', email: '', phone: '', password: '', verificationChannel: 'email', planTier: 'SOLO_FREE' };

export default function PlatformFreelancers() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(blankForm);

  function load() {
    setLoading(true);
    listFreelancers().then(setData).catch(() => toast.error('Failed to load freelancers')).finally(() => setLoading(false));
  }

  useEffect(load, []);
  async function changePlan(id, planTier) { try { await updateSoloSubscription(id, { planTier }); toast.success('Plan updated'); load(); } catch (error) { toast.error(error.response?.data?.message || 'Failed to update plan'); } }
  async function removeSubscription(account) { if (!window.confirm(`Delete the subscription for ${account.name}?`)) return; try { await deleteSoloSubscription(account.id); toast.success('Subscription deleted'); load(); } catch (error) { toast.error(error.response?.data?.message || 'Failed to delete subscription'); } }
  async function changeStatus(id, isActive) { try { await updateSoloStatus(id, isActive); toast.success('Status updated'); load(); } catch (error) { toast.error(error.response?.data?.message || 'Failed to update status'); } }
  function showPaymentDetails(account) { const payment = account.paymentDetails; if (!payment) return; window.alert(`Payment details\n\nPlan: ${account.plan?.name || '—'}\nStatus: ${account.subscriptionStatus || '—'}\nRazorpay order: ${payment.razorpayOrderId || 'Not available'}\nRazorpay payment: ${payment.razorpayPaymentId || 'Not available'}\nPaid at: ${payment.paidAt ? new Date(payment.paidAt).toLocaleString() : 'Not paid'}\nStarted: ${payment.startedAt ? new Date(payment.startedAt).toLocaleString() : '—'}\nPeriod ends: ${payment.currentPeriodEnd ? new Date(payment.currentPeriodEnd).toLocaleString() : '—'}`); }
  async function remove(account) { if (!window.confirm(`Delete ${account.name}'s solo account?`)) return; try { await deletePlatformSolo(account.id); toast.success('Solo account deleted'); load(); } catch (error) { toast.error(error.response?.data?.message || 'Failed to delete account'); } }
  async function create(event) { event.preventDefault(); try { await platformCreateSolo({ ...form, phone: form.phone || null }); toast.success('Solo account created pending verification'); setForm(blankForm); setShowForm(false); load(); } catch (error) { toast.error(error.response?.data?.message || 'Failed to create account'); } }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold text-brand-900">Freelancers</h1><p className="mt-1 text-sm text-slate-500">Individual workspaces and subscription metadata.</p></div><button type="button" onClick={() => setShowForm((value) => !value)} className="rounded-lg bg-brand-600 px-3 py-2 text-sm font-semibold text-white">+ Add Solo</button></div>
      {showForm && <form onSubmit={create} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><input required placeholder="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input placeholder="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input required minLength={8} type="password" placeholder="Temporary password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><select value={form.verificationChannel} onChange={(e) => setForm({ ...form, verificationChannel: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="email">Verify by email</option><option value="whatsapp">Verify by WhatsApp</option></select><select value={form.planTier} onChange={(e) => setForm({ ...form, planTier: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="SOLO_FREE">Solo Free</option><option value="SOLO_PRO">Solo Pro</option><option value="SOLO_BUSINESS">Solo Business</option></select><button className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Create pending Solo account</button></form>}
      <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-sm text-slate-700"><thead className="border-b border-slate-200 bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Subscription</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody>{data.map((account) => <tr key={account.id} className="border-b border-slate-100 last:border-0"><td className="px-4 py-3 font-medium text-slate-900">{account.name}</td><td className="px-4 py-3">{account.email}</td><td className="px-4 py-3"><select value={account.plan?.tier || ''} onChange={(event) => changePlan(account.id, event.target.value)} className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs text-slate-700"><option value="">No subscription</option>{plans.map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></td><td className="px-4 py-3">{account.subscriptionStatus || '—'}{account.subscriptionStatus && <button type="button" onClick={() => removeSubscription(account)} className="ml-2 text-rose-600 hover:underline">Delete subscription</button>}</td><td className="px-4 py-3">{account.paymentDetails ? <button type="button" onClick={() => showPaymentDetails(account)} className="text-brand-600 hover:underline">Payment details</button> : '—'}</td><td className="px-4 py-3"><select value={account.isActive ? 'ACTIVE' : 'INACTIVE'} onChange={(event) => changeStatus(account.id, event.target.value === 'ACTIVE')} className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs text-slate-700"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></td><td className="whitespace-nowrap px-4 py-3 text-right"><button type="button" onClick={() => remove(account)} className="text-rose-600 hover:underline">Delete</button></td></tr>)}{!loading && !data.length && <tr><td colSpan={7} className="px-4 py-6 text-center text-slate-500">No freelancers yet.</td></tr>}</tbody></table></div>
    </div>
  );
}
